[fix:git-repos-backup] GitHub action fix

diff --git a/.github/workflows/git-repos-backup-docker-build-push.yml b/.github/workflows/git-repos-backup-docker-build-push.yml
--- a/.github/workflows/git-repos-backup-docker-build-push.yml
+++ b/.github/workflows/git-repos-backup-docker-build-push.yml
@@ -31,6 +31,15 @@ jobs:
           fi
           echo "tags=$TAGS" >> $GITHUB_OUTPUT
 
+      - name: Debug Build Context
+        run: |
+          cd ./git-repos-backup
+          ls -la
+          ls -la cmd/git-repos-backup/ || echo "cmd/git-repos-backup directory not found"
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
       - name: Build and push Docker image
         uses: docker/build-push-action@v3
         with:
